#resilience4j.bulkhead:
#  instances:
#    orderService:
#      maxWaitDuration: 3000
#      maxConcurrentCalls: 5

resilience4j.thread-pool-bulkhead:
  instances:
    orderService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
